# Generated by Django 3.2.16 on 2024-07-19 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название эмоции')),
                ('descriprion', models.TextField(verbose_name='Описание эмоции')),
            ],
            options={
                'verbose_name': 'эмоция',
                'verbose_name_plural': 'Эмоции',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='ФИО пользователя')),
                ('tlg_id', models.PositiveIntegerField(unique=True, verbose_name='ID диалога пользователя')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='PresetHelpTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текстовое описание подсказки')),
            ],
            options={
                'verbose_name': 'базовая подсказка',
                'verbose_name_plural': 'Базовые подсказки',
            },
        ),
        migrations.CreateModel(
            name='PersonsHelpTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текстовое описание подсказки')),
                ('is_on', models.BooleanField(default=True, verbose_name='Показывать')),
                ('likeliness', models.PositiveSmallIntegerField(default=100, verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personstips', to='selfcare.person', verbose_name='Пользователь')),
                ('preset_tip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personstips', to='selfcare.presethelptip', verbose_name='Базовая подсказка')),
            ],
            options={
                'verbose_name': 'подсказка пользователя',
                'verbose_name_plural': 'Подсказки конкретного пользователя',
            },
        ),
    ]
