# Generated by Django 3.2.16 on 2024-07-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfcare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tlg_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='ID диалога пользователя'),
        ),
    ]
