# Generated by Django 3.2.16 on 2024-07-19 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfcare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Что я сейчас чувствую')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moodtracks', to='selfcare.person', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'чувство',
                'verbose_name_plural': 'Чувства',
            },
        ),
    ]
