# Generated by Django 3.2.16 on 2024-07-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfcare', '0002_alter_person_tlg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название эмоции')),
                ('descriprion', models.TextField(verbose_name='Описание эмоции')),
            ],
            options={
                'verbose_name': 'эмоция',
                'verbose_name_plural': 'Эмоции',
            },
        ),
        migrations.AlterModelOptions(
            name='personshelptips',
            options={'verbose_name': 'подсказка пользователя', 'verbose_name_plural': 'Подсказки конкретного пользователя'},
        ),
    ]
